<<<<<<< HEAD
# Site settings
title: Richard A.I. Bethlehem
email: rb643@medschl.cam.ac.uk
baseurl: /blog/ # the subpath of your site, e.g. /blog/
permalink: /blog/:year-:month-:day-:title/
# plugins
gems: [jekyll-paginate]
# pagination
paginate: 5
paginate_path: "/blog/page:num"

# for jekyll-rss
name: Richard Bethlehem's blog
description: Statistics, data, and cognitive science. 

# User setting
owner: Richard Bethlehem
twitter_username: rai_bethlehem
github_username: rb643
address:
 - line: 857 King's College
 - line: Cambridge, UK
copyright: rb643

# # API settings
# google_api_key:

# Build settings
markdown: kramdown
# exclude: [presentations, pubs]
=======
theme: jekyll-theme-slate
>>>>>>> origin/master
